# Configuración del puerto del servidor
server.port=8080

# Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/rs_ecomerch?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate el traductor de Java a SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect